{
 "title": "xjoin-Kafka-Connectors",
 "tags": [
  "platform-health",
  "xjoin"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Restarts",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{container=\"xjoin-kafka-connect\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{container=\"xjoin-kafka-connect\"})"
    }
   ]
  },
  {
   "title": "Processed Messages",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(kafka_consumergroup_group_offset{topic=~\".*xjoin.*\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container=\"xjoin-kafka-connect\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "xjoin connectors",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum (kafka_connect_connect_worker_metrics_connector_running_task_count{connector=~\"xjoin.*\"}) by (connector)",
     "legendFormat": "{{connector}}"
    },
    {
     "expr": "sum (kafka_connect_connect_worker_metrics_connector_paused_task_count{connector=~\"xjoin.*\"}) by (connector)",
     "legendFormat": "{{connector}}"
    },
    {
     "expr": "sum (kafka_connect_connect_worker_metrics_connector_failed_task_count{connector=~\"xjoin.*\"}) by (connector)",
     "legendFormat": "{{connector}}"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{container=\"xjoin-kafka-connect\"}[$__range]))",
     "legendFormat": "Pod Restarts"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 2 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{container=\"xjoin-kafka-connect\"})",
     "legendFormat": "Pods"
    }
   ]
  },
  {
   "title": "Incoming Message Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (topic) (rate(kafka_server_brokertopicmetrics_messagesin_total{topic=~\".*xjoin\\\\..*\"}[1m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (topic) (kafka_consumergroup_group_lag{topic=~\".*xjoin.*\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Consumed Message Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (topic, group) (rate(kafka_consumergroup_group_offset{topic=~\".*xjoin.*\"}[1m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Lag Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg by (topic) (kafka_consumergroup_group_lag_seconds{topic=~\".*xjoin.*\"})",
     "legendFormat": "avg/{{topic}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"xjoin-kafka-connect\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}