apiVersion: v1
kind: Template
metadata:
  name: xjoin-search
objects:

- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: xjoin-search
  spec:
    envName: ${ENV_NAME}
    testing:
      iqePlugin: xjoin
    dependencies:
      - host-inventory
    optionalDependencies:
      - xjoin-api-gateway
    deployments:
    - name: api
      minReplicas: ${{NUM_REPLICAS}}
      webServices:
        private:
          enabled: true
      podSpec:
        image: ${IMAGE}:${IMAGE_TAG}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: metrics
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: metrics
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        env:
          - name: LOG_LEVEL
            value: ${LOG_LEVEL}
          - name: LOG_PRETTY
            value: ${LOG_PRETTY}
          - name: NODE_ENV
            value: ${NODE_ENV}
          - name: ES_NODES
            valueFrom:
              secretKeyRef:
                key: endpoint
                name: xjoin-elasticsearch
          - name: ES_USERNAME
            value: ${ES_USERNAME}
          - name: ES_PASSWORD
            value: ${ES_PASSWORD}
          - name: HOSTS_INDEX
            value: ${HOSTS_INDEX}

        resources:
          limits:
            cpu: ${CPU_LIMITS}
            memory: ${MEMORY_LIMITS}
          requests:
            cpu: ${CPU_REQUESTS}
            memory: ${MEMORY_REQUESTS}

    jobs:
    - name: heartbeat
      schedule: ${HEARTBEAT_SCHEDULE}
      suspend: ${{HEARTBEAT_SUSPEND}}
      podSpec:
        image: ${HEARTBEAT_IMAGE}:${HEARTBEAT_IMAGE_TAG}
        restartPolicy: Never
        env:
          - name: INGRESS_HOST
            value: ${INGRESS_HOST}
          - name: INGRESS_PORT
            value: ${INGRESS_PORT}
          - name: INGRESS_PROTOCOL
            value: ${INGRESS_PROTOCOL}
        resources:
          limits:
            cpu: 51m
            memory: 51Mi
          requests:
            cpu: 50m
            memory: 50Mi

# this service proxies requests for the old URL (xjoin-search:4000) to the clowderized service (xjoin-search-api:10000)
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: xjoin-search
    name: xjoin-search
  spec:
    ports:
    - port: 4000
      protocol: TCP
      targetPort: private
    selector:
      pod: xjoin-search-api

parameters:
- name: LOG_LEVEL
  value: debug
- name: LOG_PRETTY
  value: 'false'
- description: Can be "production", "development", "test"
  name: NODE_ENV
  value: production
- name: HOSTS_INDEX
  value: xjoin.inventory.hosts
- name: CPU_REQUESTS
  value: 100m
- name: CPU_LIMITS
  value: 200m
- name: MEMORY_REQUESTS
  value: 256Mi
- name: MEMORY_LIMITS
  value: 512Mi
- name: NUM_REPLICAS
  value: '1'
- name: ES_USERNAME
  value: ''
- name: ES_PASSWORD
  value: ''

- name: INGRESS_HOST
  value: ingress-service
- name: INGRESS_PORT
  value: '8000'
- name: INGRESS_PROTOCOL
  value: 'http'
- name: HEARTBEAT_IMAGE
  value: 'quay.io/cloudservices/inventory-heartbeat'
- name: HEARTBEAT_IMAGE_TAG
  value: 'latest'
- name: HEARTBEAT_SUSPEND
  value: 'true'
- name: HEARTBEAT_SCHEDULE
  value: '@hourly'

- name: IMAGE_TAG
  required: true
- name: IMAGE
  value: quay.io/cloudservices/xjoin-search

- description : ClowdEnvironment name
  name: ENV_NAME
  required: true
