
---
name: Validation

on:
- pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    container: node:12-slim

    steps:
    - uses: actions/checkout@v2
    - run: npm ci

    - run: npm run compile
    - run: npm run lint

    - name: Configure sysctl limits
      run: |
        sudo swapoff -a
        sudo sysctl -w vm.swappiness=1
        sudo sysctl -w fs.file-max=262144
        sudo sysctl -w vm.max_map_count=262144

    - name: Runs Elasticsearch
      uses: elastic/elastic-github-actions/elasticsearch@master
      with:
        stack-version: 7.6.0

    - run: npm run verify
