# This workflow updates xjoin-schema to support the latest changes to
# the system_profile schema from inventory-schemas.
# The workflow is triggered by a workflow in the inventory-schema repo
# that runs when a change to the system profile schema is merged.

name: update mapping

on:
  schedule:
    - cron: "5 0 * * *"
  workflow_dispatch:

jobs:
  update_mapping:
    runs-on: ubuntu-latest

    steps:
      - name: Check out xjoin-config
        uses: actions/checkout@v3
      - name: Check out schema repo to copy current schema from
        uses: actions/checkout@v3
        with:
          repository: RedHatInsights/inventory-schemas
          path: ./inventory-schemas
      - name: Set vars
        id: vars
        run: |
          git config user.name 'GitHub Actions' 
          git config user.email 'actions@github.com'
          echo "schema_sha=$(git ls-remote https://github.com/RedHatInsights/inventory-schemas.git master | cut -c -7)" >> $GITHUB_OUTPUT
      - name: update schema file
        run: |
          cp inventory-schemas/schemas/system_profile/v1.yaml inventory-schemas/system_profile_schema.yaml
          echo "${{ steps.vars.outputs.schema_sha }}" >> inventory-schemas/system_profile_schema_sha.txt
      - name: update mapping from schema
        run: |
          cd scripts
          npm ci
          npm run updateFromSchema
          git diff
          git add -u
          git commit -m "updated xjoin-search to support schema changes. SHA: ${{ steps.vars.outputs.schema_sha }}" || echo "No new changes"
      - name: remove schema submodule
        run: rm -r inventory-schemas
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          base: master
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: system_profile_schema_update
          branch-suffix: short-commit-hash
          delete-branch: true
          title: '[Automated] Update mapping'
          body: |
            Updated xjoin-search to support the latest inventory-schemas changes
